### ISSUE TITLE
Idee: togglebare banen en prefix verplichting togglebaar

### ISSUE THREAD

**Issue by rickjuhh** [MrWouterNL/MinetopiaFarms#10]
Ik heb 2 ideeën:

1: Dat je in de config kan aan passen welke banen aan en uit staan

2: en dat je niet meteen een prefix heb of dat je dat kan uit zetten

[Tags @MrWouterNL @MLGEditz @YWatchman @ThomasKoreman  ]

**Comment by MrWouterNL** [comment]
Je ideetje 1x posten is genoeg, Rick. Ik werk zelf niet meer actief aan MTFarms, het is opensource (dus die tag is vrij overbodig)

Als iemand dit op wil pakken feel free.

**Comment by rickjuhh** [comment]
Die 2e was perongelijk

**Comment by ThomasKoreman** [comment]
Thanks for the mention. Maar zoals Wouter al zegt, iedereen zou het kunnen aanpassen

**Comment by stijnb1234** [comment]
Beide zitten er inmiddels in. Kan gesloten worden.
