### ISSUE TITLE
Idee

### ISSUE THREAD

**Issue by RubenZW** [MrWouterNL/MinetopiaFarms#7]
Misschien kan je maken dat je een npc kan spawnen en als je daarop klikt verkoop je de resources van jouw baan.. (Als je me de badge wil sturen kan je me contacteren via discord: Ruben || DJ || Youtuber#4689 )

**Comment by MrWouterNL** [comment]
Chief, this ain't it. Badges krijg je als je pull requests maakt, niet door ideeën te bedenken.

**Comment by DeveloperBoy** [comment]
Kan dicht. #8 voegt dit toe.
