### ISSUE TITLE
Idee: nether wart farmen, player-to-player handelsysteem

### ISSUE THREAD

**Issue by ThomasKoreman** [MrWouterNL/MinetopiaFarms#9]
Ik heb 2 ideeën:

1. Nether Wart farmen - Hierdoor zouden mensen ook potions kunnen gaan maken en verkopen.
2. Handel met andere spelers - Op het platteland wordt veel gebruik gemaakt van handel. Nu bestaan er al wel de sell signs. Maar wat als je nou ook met andere spelers kon ruilen?

**Comment by rickjuhh** [comment]
Ik heb 2 ideeën:

1: Dat je in de config kan aan passen welke banen aan en uit staan

2: en dat je niet meteen een prefix heb of dat je dat kan uit   zetten



[Tags @MrWouterNL ]

**Comment by DanielvdSpoel** [comment]
Hoe zie je dit ruilen met andere spelers dan voor je?
